on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Cloudbase action example
    steps:
      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: ./
        with:
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          envId: ${{ secrets.ENV_ID }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.deployStatic.outputs.time }}"
