on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Cloudbase action example
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action
        with:
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          envId: ${{ secrets.ENV_ID }}
          staticSrcPath: build
      - name: Get the output time
        run: echo "The time was ${{ steps.deployStatic.outputs.time }}"
